#ansible is "run once, apply to N hosts"
#"web" is the group name. You can have multiple lines under the "web" group for each VM. Currently it's just one VM
#ansible-vm1 is a friendly name that doesn't HAVE to match the actual Azure VM name, but it's sensible that it does.
#ansible_host is the actual IP Ansible connects to
#ansible_user is the Azure user who logs into it
[web]
ansible-vm1 ansible_host=20.9.54.140 ansible_user=azureuser
#ansible-vm2 ansible_host=<vm2-ip> ansible_user=azureuser